// 자주 쓰는 식재료의 카테고리와 구체적인 보관 팁 모음.
// - name: 정확히 이 이름으로 입력했을 때 매칭되는 기준값 (예: '소세지'와 '소시지'처럼
//   흔히 같이 쓰이는 표기가 있으면 각각 별도 항목으로 추가한다)
// - category: 이름 입력 시 카테고리 자동 추천에 사용. src/features/settings/defaults.js의
//   DEFAULT_INGREDIENT_CATEGORIES에 있는 이름과 정확히 같아야 한다.
// - tip: 있으면 상세보기에서 카테고리 기본 안내 대신 이 팁을 보여줌 (없어도 되고,
//   없으면 카테고리 기본 정보로 자동 대체된다)
//
// 항목을 더 추가하려면: 아래 해당 카테고리 배열에 { name, category, tip } 객체를
// 추가하면 끝. 카테고리 자동 추천/보관 팁 화면 모두 이 목록 하나만 보고 동작한다.
//
// 이 목록은 빠른 재료 등록(+ 버튼)의 카드 선택 화면에도 그대로 쓰인다. 카드에는
// 별도 이미지 대신 카테고리 기본 아이콘(categoryDefaults.js의 getCategoryIcon)을
// 보여준다 - 수백 개 항목마다 이미지를 미리 준비/생성할 필요가 없도록 하기 위함.
export const KNOWN_INGREDIENTS = [
  // 채소
  { name: '청양고추', category: '채소', tip: '잘게 썰어서 소분한 뒤 냉동 보관하면 오래 두고 쓸 수 있어요.' },
  { name: '대파', category: '채소', tip: '송송 썰어 소분해 냉동하면 필요할 때 바로 꺼내 쓸 수 있어요.' },
  { name: '마늘', category: '채소', tip: '다져서 소분한 뒤 냉동 보관하면 오래가요.' },
  { name: '양파', category: '채소', tip: '신문지에 싸서 서늘하고 통풍이 잘 되는 곳에 두면 냉장 보관 없이도 오래가요.' },
  { name: '감자', category: '채소', tip: '사과와 함께 보관하면 사과에서 나오는 가스 때문에 싹이 늦게 나요.' },
  { name: '당근', category: '채소', tip: '페이퍼타월로 감싸 비닐팩에 넣어 냉장 보관하면 무르는 걸 늦출 수 있어요.' },
  { name: '오이', category: '채소', tip: '물기를 완전히 제거하고 하나씩 랩으로 싸서 보관하면 오래가요.' },
  { name: '상추', category: '채소', tip: '젖은 키친타월로 감싸 밀폐용기에 넣으면 싱싱함이 오래 유지돼요.' },
  { name: '시금치', category: '채소', tip: '데쳐서 물기를 짠 뒤 소분해 냉동하면 오래 보관할 수 있어요.' },
  { name: '애호박', category: '채소', tip: '자른 단면을 랩으로 감싸면 마르는 걸 막을 수 있어요.' },
  { name: '브로콜리', category: '채소', tip: '살짝 데친 뒤 소분해서 냉동하면 오래 두고 먹을 수 있어요.' },
  { name: '깻잎', category: '채소', tip: '키친타월을 깔고 켜켜이 쌓아 밀폐용기에 넣으면 오래가요.' },
  { name: '무', category: '채소', tip: '신문지로 감싸 냉장 보관하면 수분 손실을 줄일 수 있어요.' },
  { name: '배추', category: '채소', tip: '겉잎으로 감싸 신문지에 싸서 냉장 보관하면 오래가요.' },
  { name: '콩나물', category: '채소', tip: '밀폐용기에 물을 자작하게 부어 냉장 보관하면 신선함이 유지돼요.' },
  { name: '숙주', category: '채소', tip: '밀폐용기에 물을 자작하게 부어 냉장 보관하면 신선함이 유지돼요.' },
  { name: '버섯', category: '채소', tip: '종이봉투에 넣어 냉장 보관하면 물러지는 걸 늦출 수 있어요.' },
  { name: '토마토', category: '채소' },
  { name: '방울토마토', category: '채소' },
  { name: '피망', category: '채소' },
  { name: '파프리카', category: '채소' },
  { name: '가지', category: '채소' },
  { name: '양배추', category: '채소', tip: '겉잎을 떼지 말고 랩으로 감싸 냉장 보관하면 오래가요.' },
  { name: '부추', category: '채소' },
  { name: '미나리', category: '채소' },
  { name: '셀러리', category: '채소' },
  { name: '단호박', category: '채소' },
  { name: '고구마', category: '채소', tip: '신문지에 싸서 서늘하고 통풍이 잘 되는 곳에 두면 오래가요 (냉장 보관은 피하세요).' },
  { name: '연근', category: '채소' },
  { name: '우엉', category: '채소' },
  { name: '열무', category: '채소' },
  { name: '얼갈이배추', category: '채소' },
  { name: '청경채', category: '채소' },
  { name: '아스파라거스', category: '채소' },
  { name: '생강', category: '채소', tip: '작게 소분해서 냉동 보관하면 필요한 만큼 꺼내 쓸 수 있어요.' },
  { name: '홍고추', category: '채소' },
  { name: '풋고추', category: '채소' },
  { name: '꽈리고추', category: '채소' },
  { name: '오크라', category: '채소' },
  { name: '콜라비', category: '채소' },
  { name: '무순', category: '채소' },
  { name: '새싹채소', category: '채소' },
  { name: '알배추', category: '채소' },
  { name: '봄동', category: '채소' },
  { name: '방울양배추', category: '채소' },
  { name: '케일', category: '채소' },
  { name: '루꼴라', category: '채소' },
  { name: '치커리', category: '채소' },
  { name: '적채', category: '채소' },
  { name: '파슬리', category: '채소', tip: '젖은 키친타월로 감싸 밀폐용기에 넣으면 오래가요.' },
  { name: '바질', category: '채소', tip: '물을 담은 컵에 줄기를 꽂아 실온에 두면 오래 두고 쓸 수 있어요.' },
  { name: '로즈마리', category: '채소' },
  { name: '애플민트', category: '채소' },
  { name: '깐마늘', category: '채소', tip: '밀폐용기에 담아 냉장 보관하면 편하게 꺼내 쓸 수 있어요.' },
  { name: '마늘종', category: '채소' },
  { name: '쪽파', category: '채소' },
  { name: '실파', category: '채소' },
  { name: '양상추', category: '채소' },
  { name: '새송이버섯', category: '채소' },
  { name: '표고버섯', category: '채소', tip: '말려서 보관하면 훨씬 오래 두고 쓸 수 있어요.' },
  { name: '느타리버섯', category: '채소' },
  { name: '팽이버섯', category: '채소' },
  { name: '양송이버섯', category: '채소' },
  { name: '목이버섯', category: '채소' },
  { name: '취나물', category: '채소' },
  { name: '고사리', category: '채소' },
  { name: '도라지', category: '채소', tip: '흙이 묻은 채로는 신문지에 싸서 냉장 보관하세요.' },
  { name: '더덕', category: '채소', tip: '흙이 묻은 채로는 신문지에 싸서 냉장 보관하세요.' },
  { name: '냉이', category: '채소' },
  { name: '쑥', category: '채소' },
  { name: '두릅', category: '채소' },
  { name: '죽순', category: '채소', tip: '삶아서 물에 담가 냉장 보관하면 아린맛이 빠지고 오래가요.' },
  { name: '마', category: '채소' },
  { name: '비트', category: '채소' },
  { name: '콜리플라워', category: '채소' },
  { name: '겨자잎', category: '채소' },
  { name: '노각', category: '채소' },

  // 과일
  { name: '바나나', category: '과일', tip: '꼭지 부분을 랩으로 감싸면 숙성 속도를 늦출 수 있어요.' },
  { name: '딸기', category: '과일', tip: '씻지 않은 상태로 밀폐용기에 넣어 냉장 보관하고, 먹기 직전에 씻으세요.' },
  { name: '사과', category: '과일', tip: '비닐팩에 넣어 냉장 보관하면 수분 손실을 막을 수 있어요.' },
  { name: '귤', category: '과일', tip: '서늘한 곳에 겹치지 않게 보관하면 무르는 걸 늦출 수 있어요.' },
  { name: '포도', category: '과일', tip: '씻지 않고 밀폐용기에 넣어 냉장 보관하고, 먹기 직전에 씻으세요.' },
  { name: '레몬', category: '과일', tip: '밀폐용기나 지퍼백에 넣어 냉장 보관하면 오래가요.' },
  { name: '아보카도', category: '과일', tip: '덜 익었으면 실온 보관, 다 익었으면 냉장 보관하세요.' },
  { name: '수박', category: '과일' },
  { name: '참외', category: '과일' },
  { name: '키위', category: '과일', tip: '단단하면 실온에서 후숙시키고, 다 익으면 냉장 보관하세요.' },
  { name: '망고', category: '과일', tip: '덜 익었으면 실온 후숙, 다 익으면 냉장 보관하세요.' },
  { name: '파파야', category: '과일', tip: '덜 익었으면 실온 후숙, 다 익으면 냉장 보관하세요.' },
  { name: '자몽', category: '과일' },
  { name: '오렌지', category: '과일' },
  { name: '체리', category: '과일', tip: '씻지 않은 상태로 밀폐용기에 넣어 냉장 보관하고, 먹기 직전에 씻으세요.' },
  { name: '블루베리', category: '과일', tip: '씻지 않은 상태로 밀폐용기에 넣어 냉장 보관하고, 오래 두려면 냉동 보관하세요.' },
  { name: '자두', category: '과일' },
  { name: '복숭아', category: '과일' },
  { name: '배', category: '과일' },
  { name: '멜론', category: '과일' },
  { name: '석류', category: '과일' },
  { name: '무화과', category: '과일' },
  { name: '유자', category: '과일' },
  { name: '한라봉', category: '과일' },
  { name: '청포도', category: '과일' },
  { name: '샤인머스캣', category: '과일' },
  { name: '천혜향', category: '과일' },
  { name: '레드향', category: '과일' },
  { name: '황금향', category: '과일' },
  { name: '금귤', category: '과일' },
  { name: '라임', category: '과일' },
  { name: '파인애플', category: '과일', tip: '자른 뒤에는 밀폐용기에 담아 냉장 보관하고 빨리 드세요.' },
  { name: '코코넛', category: '과일' },
  { name: '두리안', category: '과일' },
  { name: '리치', category: '과일' },
  { name: '용과', category: '과일' },
  { name: '구아바', category: '과일' },
  { name: '패션프루트', category: '과일' },
  { name: '산딸기', category: '과일' },
  { name: '블랙베리', category: '과일' },
  { name: '크랜베리', category: '과일' },
  { name: '대추', category: '과일' },
  { name: '곶감', category: '과일' },
  { name: '홍시', category: '과일' },
  { name: '단감', category: '과일' },
  { name: '살구', category: '과일' },
  { name: '매실', category: '과일', tip: '설탕에 재워 청을 담그면 오래 두고 활용할 수 있어요.' },
  { name: '앵두', category: '과일' },
  { name: '오디', category: '과일' },

  // 육류
  { name: '삼겹살', category: '육류', tip: '소분해서 랩으로 밀착 포장한 뒤 냉동하면 오래 보관할 수 있어요.' },
  { name: '목살', category: '육류', tip: '소분해서 랩으로 밀착 포장한 뒤 냉동하면 오래 보관할 수 있어요.' },
  { name: '안심', category: '육류', tip: '핏물을 제거하고 랩으로 밀착 포장한 뒤 냉동 보관하세요.' },
  { name: '등심', category: '육류', tip: '핏물을 제거하고 랩으로 밀착 포장한 뒤 냉동 보관하세요.' },
  { name: '갈비', category: '육류', tip: '소분해서 랩으로 밀착 포장한 뒤 냉동하면 오래 보관할 수 있어요.' },
  { name: '닭가슴살', category: '육류', tip: '한 끼 분량씩 소분해 냉동 보관하면 편리해요.' },
  { name: '닭다리', category: '육류' },
  { name: '닭날개', category: '육류' },
  { name: '닭봉', category: '육류' },
  { name: '닭안심', category: '육류' },
  { name: '다진고기', category: '육류', tip: '얇게 펴서 냉동하면 필요한 만큼만 부러뜨려 쓸 수 있어요.' },
  { name: '다짐육', category: '육류', tip: '얇게 펴서 냉동하면 필요한 만큼만 부러뜨려 쓸 수 있어요.' },
  { name: '소고기', category: '육류', tip: '핏물을 제거하고 랩으로 밀착 포장한 뒤 냉동 보관하세요.' },
  { name: '돼지고기', category: '육류' },
  { name: '베이컨', category: '육류', tip: '낱장으로 분리해 랩에 싸서 냉동하면 필요한 만큼 꺼내 쓸 수 있어요.' },
  { name: '소세지', category: '육류', tip: '개봉 후 소분해서 냉동 보관하면 오래 두고 먹을 수 있어요.' },
  { name: '소시지', category: '육류', tip: '개봉 후 소분해서 냉동 보관하면 오래 두고 먹을 수 있어요.' },
  { name: '햄', category: '육류', tip: '개봉 후 밀폐용기에 담아 냉장 보관하세요.' },
  { name: '스팸', category: '육류' },
  { name: '훈제오리', category: '육류' },
  { name: '항정살', category: '육류' },
  { name: '가브리살', category: '육류' },
  { name: '앞다리살', category: '육류' },
  { name: '뒷다리살', category: '육류' },
  { name: '갈매기살', category: '육류' },
  { name: '차돌박이', category: '육류' },
  { name: '양지', category: '육류' },
  { name: '사태', category: '육류' },
  { name: '우삼겹', category: '육류' },
  { name: '대창', category: '육류', tip: '손질 후 밀폐용기에 담아 냉동 보관하세요.' },
  { name: '곱창', category: '육류', tip: '손질 후 밀폐용기에 담아 냉동 보관하세요.' },
  { name: '막창', category: '육류', tip: '손질 후 밀폐용기에 담아 냉동 보관하세요.' },
  { name: '닭모래집', category: '육류' },
  { name: '오리고기', category: '육류' },
  { name: '훈제삼겹살', category: '육류' },
  { name: '불고기용고기', category: '육류', tip: '한 번 쓸 분량씩 소분해서 냉동하면 편리해요.' },
  { name: '국거리용고기', category: '육류', tip: '한 번 쓸 분량씩 소분해서 냉동하면 편리해요.' },
  { name: '양고기', category: '육류' },
  { name: '백숙용닭', category: '육류' },
  { name: '폭립', category: '육류' },
  { name: '프랑크소시지', category: '육류' },
  { name: '비엔나소시지', category: '육류' },
  { name: '런천미트', category: '육류' },
  { name: '육포', category: '육류' },
  { name: '순대', category: '육류' },
  { name: '편육', category: '육류', tip: '진공포장 상태 그대로 냉장 또는 냉동 보관하세요.' },
  { name: '족발', category: '육류', tip: '진공포장 상태 그대로 냉장 또는 냉동 보관하세요.' },
  { name: '보쌈용고기', category: '육류' },
  { name: '미트볼', category: '육류' },

  // 수산물
  { name: '고등어', category: '수산물', tip: '손질 후 한 마리씩 랩에 싸서 냉동 보관하면 오래가요.' },
  { name: '갈치', category: '수산물', tip: '손질 후 한 마리씩 랩에 싸서 냉동 보관하면 오래가요.' },
  { name: '삼치', category: '수산물' },
  { name: '참치', category: '수산물' },
  { name: '동태', category: '수산물' },
  { name: '황태', category: '수산물' },
  { name: '멸치', category: '수산물', tip: '밀폐용기에 담아 냉동 보관하면 눅눅해지지 않아요.' },
  { name: '새우', category: '수산물', tip: '손질 후 소분해서 냉동하면 필요한 만큼 꺼내 쓸 수 있어요.' },
  { name: '오징어', category: '수산물', tip: '손질 후 밀폐용기에 담아 냉동 보관하세요.' },
  { name: '문어', category: '수산물' },
  { name: '낙지', category: '수산물' },
  { name: '조개', category: '수산물', tip: '소금물에 해감한 뒤 밀폐용기에 담아 냉장 보관하고, 최대한 빨리 드세요.' },
  { name: '홍합', category: '수산물' },
  { name: '전복', category: '수산물' },
  { name: '굴', category: '수산물', tip: '흐르는 물에 헹구지 말고 밀폐용기에 담아 냉장 보관하고, 최대한 빨리 드세요.' },
  { name: '게', category: '수산물' },
  { name: '연어', category: '수산물' },
  { name: '미역', category: '수산물', tip: '건조 상태로 밀폐용기에 담아 서늘하고 건조한 곳에 보관하세요.' },
  { name: '다시마', category: '수산물', tip: '건조 상태로 밀폐용기에 담아 서늘하고 건조한 곳에 보관하세요.' },
  { name: '김', category: '수산물', tip: '밀폐용기에 담아 습기가 없는 곳에 보관하세요.' },
  { name: '임연수어', category: '수산물' },
  { name: '코다리', category: '수산물' },
  { name: '병어', category: '수산물' },
  { name: '조기', category: '수산물' },
  { name: '굴비', category: '수산물' },
  { name: '장어', category: '수산물' },
  { name: '아귀', category: '수산물' },
  { name: '가자미', category: '수산물' },
  { name: '광어', category: '수산물' },
  { name: '우럭', category: '수산물' },
  { name: '도미', category: '수산물' },
  { name: '명태', category: '수산물' },
  { name: '북어', category: '수산물' },
  { name: '꽁치', category: '수산물' },
  { name: '정어리', category: '수산물' },
  { name: '주꾸미', category: '수산물' },
  { name: '꼴뚜기', category: '수산물' },
  { name: '꽃게', category: '수산물', tip: '손질 후 소분해서 냉동 보관하면 오래 두고 쓸 수 있어요.' },
  { name: '대게', category: '수산물', tip: '손질 후 소분해서 냉동 보관하면 오래 두고 쓸 수 있어요.' },
  { name: '킹크랩', category: '수산물' },
  { name: '랍스터', category: '수산물' },
  { name: '가리비', category: '수산물' },
  { name: '바지락', category: '수산물', tip: '소금물에 해감한 뒤 밀폐용기에 담아 냉장 보관하세요.' },
  { name: '모시조개', category: '수산물', tip: '소금물에 해감한 뒤 밀폐용기에 담아 냉장 보관하세요.' },
  { name: '소라', category: '수산물' },
  { name: '멍게', category: '수산물' },
  { name: '해삼', category: '수산물' },
  { name: '파래', category: '수산물' },
  { name: '톳', category: '수산물' },
  { name: '매생이', category: '수산물' },
  { name: '크래미', category: '수산물' },
  { name: '명란젓', category: '수산물' },
  { name: '새우젓', category: '수산물' },
  { name: '액젓', category: '수산물' },

  // 유제품
  { name: '우유', category: '유제품', tip: '문쪽보다 안쪽 선반에 보관하면 온도 변화가 적어 더 오래가요.' },
  { name: '치즈', category: '유제품', tip: '랩으로 밀착 포장한 뒤 밀폐용기에 넣어 냉장 보관하세요.' },
  { name: '요거트', category: '유제품', tip: '개봉 후에는 최대한 빨리 섭취하는 게 좋아요.' },
  { name: '버터', category: '유제품', tip: '랩으로 감싸 냉장 또는 냉동 보관하면 산패를 늦출 수 있어요.' },
  { name: '계란', category: '유제품' },
  { name: '생크림', category: '유제품', tip: '개봉 후 최대한 빨리 사용하는 게 좋아요.' },
  { name: '크림치즈', category: '유제품' },
  { name: '연유', category: '유제품' },
  { name: '저지방우유', category: '유제품' },
  { name: '락토프리우유', category: '유제품' },
  { name: '슬라이스치즈', category: '유제품' },
  { name: '모짜렐라치즈', category: '유제품', tip: '개봉 후 밀폐용기에 물과 함께 담가 냉장 보관하면 촉촉함이 유지돼요.' },
  { name: '파마산치즈', category: '유제품' },
  { name: '체다치즈', category: '유제품' },
  { name: '카망베르치즈', category: '유제품' },
  { name: '리코타치즈', category: '유제품' },
  { name: '마스카포네치즈', category: '유제품' },
  { name: '그릭요거트', category: '유제품' },
  { name: '액상요거트', category: '유제품' },
  { name: '코티지치즈', category: '유제품' },
  { name: '무염버터', category: '유제품' },
  { name: '가염버터', category: '유제품' },
  { name: '마가린', category: '유제품' },
  { name: '휘핑크림', category: '유제품' },
  { name: '메추리알', category: '유제품', tip: '삶은 뒤 밀폐용기에 담아 냉장 보관하세요.' },
  { name: '오리알', category: '유제품' },

  // 곡류/가공식품
  { name: '쌀', category: '곡류/가공식품', tip: '밀폐용기에 담아 서늘하고 건조한 곳에 보관하세요.' },
  { name: '식빵', category: '곡류/가공식품', tip: '냉동 보관하면 곰팡이 없이 오래 두고 먹을 수 있어요.' },
  { name: '두부', category: '곡류/가공식품', tip: '물에 담가 냉장 보관하고, 물을 매일 갈아주면 더 오래가요.' },
  { name: '라면', category: '곡류/가공식품' },
  { name: '미숫가루', category: '곡류/가공식품', tip: '밀폐용기에 담아 습기가 없는 곳에 실온 보관하세요.' },
  { name: '밀가루', category: '곡류/가공식품', tip: '밀폐용기에 담아 습기가 없는 곳에 보관하세요 (개봉 후 냉장 보관하면 벌레를 막을 수 있어요).' },
  { name: '빵가루', category: '곡류/가공식품' },
  { name: '국수', category: '곡류/가공식품' },
  { name: '소면', category: '곡류/가공식품' },
  { name: '파스타면', category: '곡류/가공식품' },
  { name: '시리얼', category: '곡류/가공식품' },
  { name: '오트밀', category: '곡류/가공식품' },
  { name: '떡', category: '곡류/가공식품', tip: '소분해서 냉동 보관하면 굳지 않고 오래 두고 먹을 수 있어요.' },
  { name: '즉석밥', category: '곡류/가공식품' },
  { name: '현미', category: '곡류/가공식품', tip: '밀폐용기에 담아 서늘하고 건조한 곳에 보관하세요.' },
  { name: '찹쌀', category: '곡류/가공식품' },
  { name: '흑미', category: '곡류/가공식품' },
  { name: '보리', category: '곡류/가공식품' },
  { name: '귀리', category: '곡류/가공식품' },
  { name: '검은콩', category: '곡류/가공식품' },
  { name: '잡곡', category: '곡류/가공식품', tip: '밀폐용기에 담아 서늘하고 건조한 곳에 보관하세요.' },
  { name: '당면', category: '곡류/가공식품' },
  { name: '우동면', category: '곡류/가공식품' },
  { name: '칼국수면', category: '곡류/가공식품' },
  { name: '냉면면', category: '곡류/가공식품' },
  { name: '쌀국수', category: '곡류/가공식품' },
  { name: '만두피', category: '곡류/가공식품' },
  { name: '또띠아', category: '곡류/가공식품' },
  { name: '모닝빵', category: '곡류/가공식품' },
  { name: '크루아상', category: '곡류/가공식품' },
  { name: '바게트', category: '곡류/가공식품' },
  { name: '베이글', category: '곡류/가공식품' },
  { name: '카스테라', category: '곡류/가공식품' },
  { name: '핫케이크가루', category: '곡류/가공식품' },
  { name: '부침가루', category: '곡류/가공식품' },
  { name: '튀김가루', category: '곡류/가공식품' },
  { name: '전분가루', category: '곡류/가공식품' },
  { name: '옥수수전분', category: '곡류/가공식품' },
  { name: '찹쌀가루', category: '곡류/가공식품' },
  { name: '베이킹파우더', category: '곡류/가공식품' },
  { name: '베이킹소다', category: '곡류/가공식품' },
  { name: '이스트', category: '곡류/가공식품', tip: '개봉 후 밀폐용기에 담아 냉장 또는 냉동 보관하세요.' },
  { name: '순두부', category: '곡류/가공식품' },
  { name: '연두부', category: '곡류/가공식품' },
  { name: '유부', category: '곡류/가공식품' },
  { name: '청국장', category: '곡류/가공식품' },
  { name: '낫또', category: '곡류/가공식품' },
  { name: '마카로니', category: '곡류/가공식품' },
  { name: '라자냐면', category: '곡류/가공식품' },
  { name: '쌀떡', category: '곡류/가공식품' },
  { name: '떡국떡', category: '곡류/가공식품' },
  { name: '가래떡', category: '곡류/가공식품' },
  { name: '인절미', category: '곡류/가공식품' },
  { name: '약과', category: '곡류/가공식품' },
  { name: '한과', category: '곡류/가공식품' },
  { name: '강정', category: '곡류/가공식품' },
  { name: '아몬드', category: '곡류/가공식품' },
  { name: '호두', category: '곡류/가공식품', tip: '밀폐용기에 담아 냉장 또는 냉동 보관하면 산패를 늦출 수 있어요.' },
  { name: '땅콩', category: '곡류/가공식품' },
  { name: '캐슈넛', category: '곡류/가공식품' },
  { name: '피스타치오', category: '곡류/가공식품' },
  { name: '잣', category: '곡류/가공식품' },
  { name: '해바라기씨', category: '곡류/가공식품' },
  { name: '건포도', category: '곡류/가공식품' },
  { name: '그래놀라', category: '곡류/가공식품' },
  { name: '뮤즐리', category: '곡류/가공식품' },
  { name: '통조림옥수수', category: '곡류/가공식품' },
  { name: '스프가루', category: '곡류/가공식품' },
  { name: '단무지', category: '곡류/가공식품' },

  // 소스/양념
  { name: '고추장', category: '소스/양념', tip: '개봉 후 냉장 보관하면 맛이 오래 유지돼요.' },
  { name: '된장', category: '소스/양념', tip: '표면을 눌러 공기와의 접촉을 줄이면 오래 보관할 수 있어요.' },
  { name: '간장', category: '소스/양념', tip: '실온 보관도 가능하지만 냉장 보관하면 풍미가 더 오래 유지돼요.' },
  { name: '고춧가루', category: '소스/양념' },
  { name: '소금', category: '소스/양념', tip: '밀폐용기에 담아 습기가 없는 곳에 실온 보관하세요.' },
  { name: '설탕', category: '소스/양념', tip: '밀폐용기에 담아 습기가 없는 곳에 실온 보관하세요.' },
  { name: '식용유', category: '소스/양념', tip: '빛을 피해 서늘한 곳에 실온 보관하세요.' },
  { name: '굴소스', category: '소스/양념', tip: '개봉 후 냉장 보관하면 맛이 오래 유지돼요.' },
  { name: '참기름', category: '소스/양념', tip: '빛을 피해 서늘한 곳에 실온 보관하세요.' },
  { name: '후추', category: '소스/양념' },
  { name: '식초', category: '소스/양념' },
  { name: '맛술', category: '소스/양념' },
  { name: '미림', category: '소스/양념' },
  { name: '청주', category: '소스/양념' },
  { name: '올리고당', category: '소스/양념' },
  { name: '물엿', category: '소스/양념' },
  { name: '케찹', category: '소스/양념' },
  { name: '마요네즈', category: '소스/양념', tip: '개봉 후 냉장 보관하세요.' },
  { name: '머스타드', category: '소스/양념' },
  { name: '카레가루', category: '소스/양념' },
  { name: '다진마늘', category: '소스/양념', tip: '개봉 후 냉장 또는 냉동 보관하세요.' },
  { name: '쌈장', category: '소스/양념' },
  { name: '초고추장', category: '소스/양념' },
  { name: '까나리액젓', category: '소스/양념' },
  { name: '다시다', category: '소스/양념' },
  { name: '치킨스톡', category: '소스/양념' },
  { name: '사골육수', category: '소스/양념', tip: '소분해서 냉동 보관하면 필요한 만큼 꺼내 쓸 수 있어요.' },
  { name: '맛간장', category: '소스/양념' },
  { name: '진간장', category: '소스/양념' },
  { name: '국간장', category: '소스/양념' },
  { name: '양조간장', category: '소스/양념' },
  { name: '어간장', category: '소스/양념' },
  { name: '발사믹식초', category: '소스/양념' },
  { name: '사과식초', category: '소스/양념' },
  { name: '현미식초', category: '소스/양념' },
  { name: '올리브유', category: '소스/양념' },
  { name: '포도씨유', category: '소스/양념' },
  { name: '카놀라유', category: '소스/양념' },
  { name: '코코넛오일', category: '소스/양념' },
  { name: '들기름', category: '소스/양념', tip: '빛을 피해 서늘한 곳에 보관하고 되도록 빨리 소비하세요.' },
  { name: '고추기름', category: '소스/양념' },
  { name: '페퍼론치노', category: '소스/양념' },
  { name: '오레가노', category: '소스/양념' },
  { name: '큐민', category: '소스/양념' },
  { name: '계피가루', category: '소스/양념' },
  { name: '짜장분말', category: '소스/양념' },
  { name: '짬뽕분말', category: '소스/양념' },
  { name: '미소된장', category: '소스/양념' },
  { name: '두반장', category: '소스/양념' },
  { name: '천일염', category: '소스/양념' },
  { name: '맛소금', category: '소스/양념' },
  { name: '흑설탕', category: '소스/양념' },
  { name: '시나몬파우더', category: '소스/양념' },
  { name: '후리가케', category: '소스/양념' },
  { name: '산초가루', category: '소스/양념' },
  { name: '와사비', category: '소스/양념', tip: '개봉 후 냉장 보관하세요.' },
  { name: '겨자', category: '소스/양념', tip: '개봉 후 냉장 보관하세요.' },
  { name: '스리라차', category: '소스/양념' },
  { name: '타바스코', category: '소스/양념' },
  { name: '데리야키소스', category: '소스/양념' },
  { name: '돈까스소스', category: '소스/양념' },
  { name: '우스터소스', category: '소스/양념' },
  { name: '칠리소스', category: '소스/양념' },
  { name: '핫소스', category: '소스/양념' },
  { name: '피자소스', category: '소스/양념' },
  { name: '토마토소스', category: '소스/양념' },
  { name: '페스토소스', category: '소스/양념' },
  { name: '춘장', category: '소스/양념', tip: '개봉 후 냉장 보관하세요.' },

  // 냉동식품
  { name: '만두', category: '냉동식품', tip: '서로 붙지 않게 지퍼백에 넣어 냉동 보관하세요.' },
  { name: '아이스크림', category: '냉동식품', tip: '온도 변화가 적은 냉동실 안쪽에 보관하면 오래가요.' },
  { name: '냉동피자', category: '냉동식품' },
  { name: '핫도그', category: '냉동식품' },
  { name: '돈까스', category: '냉동식품' },
  { name: '어묵', category: '냉동식품', tip: '개봉 후 밀폐용기에 담아 냉장 보관하고, 오래 두려면 냉동 보관하세요.' },
  { name: '냉동새우', category: '냉동식품', tip: '한번 해동한 뒤 재냉동하지 않는 게 좋아요.' },
  { name: '냉동블루베리', category: '냉동식품' },
  { name: '냉동딸기', category: '냉동식품' },
  { name: '냉동채소믹스', category: '냉동식품' },
  { name: '냉동감자튀김', category: '냉동식품' },
  { name: '냉동옥수수', category: '냉동식품' },
  { name: '냉동단호박', category: '냉동식품' },
  { name: '냉동떡갈비', category: '냉동식품' },
  { name: '냉동함박스테이크', category: '냉동식품' },
  { name: '냉동치킨너겟', category: '냉동식품' },
  { name: '냉동새우튀김', category: '냉동식품' },
  { name: '냉동볶음밥', category: '냉동식품' },
  { name: '냉동파이', category: '냉동식품' },
  { name: '냉동김밥', category: '냉동식품' },
  { name: '아이스바', category: '냉동식품' },

  // 음료
  { name: '두유', category: '음료', tip: '개봉 후 냉장 보관하고 빨리 섭취하세요.' },
  { name: '주스', category: '음료' },
  { name: '콜라', category: '음료', tip: '탄산이 빠지지 않게 뚜껑을 꼭 닫아 냉장 보관하세요.' },
  { name: '사이다', category: '음료', tip: '탄산이 빠지지 않게 뚜껑을 꼭 닫아 냉장 보관하세요.' },
  { name: '탄산수', category: '음료' },
  { name: '커피', category: '음료' },
  { name: '원두', category: '음료', tip: '밀폐용기에 담아 서늘하고 건조한 곳에 보관하세요.' },
  { name: '녹차', category: '음료' },
  { name: '홍차', category: '음료' },
  { name: '이온음료', category: '음료' },
  { name: '맥주', category: '음료' },
  { name: '소주', category: '음료' },
  { name: '와인', category: '음료', tip: '눕혀서 서늘하고 어두운 곳에 보관하세요.' },
  { name: '막걸리', category: '음료', tip: '병을 흔들어 섞은 뒤 냉장 보관하고 빨리 드세요.' },
  { name: '생수', category: '음료' },
  { name: '에이드', category: '음료' },
  { name: '식혜', category: '음료' },
  { name: '수정과', category: '음료' },
  { name: '매실차', category: '음료' },
  { name: '유자차', category: '음료' },
  { name: '대추차', category: '음료' },
  { name: '보리차', category: '음료' },
  { name: '옥수수수염차', category: '음료' },
  { name: '둥굴레차', category: '음료' },
  { name: '헛개차', category: '음료' },
  { name: '캔커피', category: '음료' },
  { name: '콜드브루', category: '음료' },
  { name: '에너지드링크', category: '음료' },
  { name: '비타민음료', category: '음료' },
  { name: '마시는요거트', category: '음료' },
  { name: '아이스티', category: '음료' },
  { name: '토마토주스', category: '음료' },
  { name: '당근주스', category: '음료' },
  { name: '스무디', category: '음료' },
  { name: '위스키', category: '음료' },
  { name: '보드카', category: '음료' },
  { name: '브랜디', category: '음료' },
  { name: '청하', category: '음료' },
  { name: '복분자주', category: '음료' },
  { name: '매실주', category: '음료' },

  // 기타
  { name: '김치', category: '기타', tip: '완전히 익으면 냉장 보관해 발효 속도를 늦추세요.' },
  { name: '깍두기', category: '기타' },
  { name: '겉절이', category: '기타' },
  { name: '총각김치', category: '기타' },
  { name: '열무김치', category: '기타' },
  { name: '백김치', category: '기타' },
  { name: '오이소박이', category: '기타' },
  { name: '장아찌', category: '기타', tip: '국물에 완전히 잠기게 보관하면 오래가요.' },
  { name: '젓갈', category: '기타' },
  { name: '도토리묵', category: '기타' },
  { name: '청포묵', category: '기타' },
  { name: '곤약', category: '기타' },
  { name: '콩자반', category: '기타' },
  { name: '멸치볶음', category: '기타' },
  { name: '진미채', category: '기타' },
]

const KNOWN_NAME_SET = new Set(KNOWN_INGREDIENTS.map((item) => item.name))

// findIngredientMatch와 달리 접두/포함 매칭 없이 정확히 이 이름 그대로
// 등록된 항목인지만 본다. 식재료 이미지를 AI로 생성할지, 카테고리 아이콘을
// 고정으로 쓸지 정하는 데 쓰인다(이 목록에 있으면 이름/카테고리가 이미
// 정확히 매칭되므로 AI 이미지를 시도하지 않는다).
export function isKnownIngredientName(rawName) {
  return KNOWN_NAME_SET.has(rawName.trim())
}

// 접두/포함 매칭(아래 typingMatch, containsMatch)은 한 글자짜리 이름(무, 쌀, 귤 등)이
// 엉뚱한 단어 속에서 우연히 겹쳐 잘못 매칭되는 걸 막기 위해 2글자 이상만 대상으로 한다.
// 예: "굴소스"의 "굴" 한 글자가 다른 항목과 겹쳐서 매칭되는 일이 없도록.
const FUZZY_MATCH_INDEX = [...KNOWN_INGREDIENTS]
  .filter((item) => item.name.length >= 2)
  .sort((a, b) => b.name.length - a.name.length)

// 입력 중인 이름과 가장 잘 맞는 항목을 찾는다.
// 정확히 일치 -> 알려진 이름이 입력값으로 시작(입력 중) -> 입력값이 알려진 이름을 포함 순으로 시도.
export function findIngredientMatch(rawName) {
  const name = rawName.trim()
  if (!name) return null

  const exact = KNOWN_INGREDIENTS.find((item) => item.name === name)
  if (exact) return exact

  const typingMatch = FUZZY_MATCH_INDEX.find((item) => item.name.startsWith(name))
  if (typingMatch) return typingMatch

  return FUZZY_MATCH_INDEX.find((item) => name.includes(item.name)) ?? null
}
